package com.dimacofi.DAO;
// Generated 13-03-2019 14:36:21 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.OneToMany;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private int idEstado;
     private String descEstado;
     
     @JsonIgnore
     @OneToMany(mappedBy="monitorDevices")
     private Set monitorDevices = new HashSet(0);

    public Estado() {
    }

	
    public Estado(int idEstado) {
        this.idEstado = idEstado;
    }
    public Estado(int idEstado, String descEstado, Set monitorDevices) {
       this.idEstado = idEstado;
       this.descEstado = descEstado;
       this.monitorDevices = monitorDevices;
    }
   
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public String getDescEstado() {
        return this.descEstado;
    }
    
    public void setDescEstado(String descEstado) {
        this.descEstado = descEstado;
    }
    public Set getMonitorDevices() {
        return this.monitorDevices;
    }
    
    public void setMonitorDevices(Set monitorDevices) {
        this.monitorDevices = monitorDevices;
    }




}


