package com.dimacofi.DAO;
// Generated 18-04-2019 13:35:06 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.OneToMany;

/**
 * Estado generated by hbm2java
 */
public class Estado implements java.io.Serializable {

    private int idEstado;
    private String descEstado;

    @JsonIgnore
    @OneToMany(mappedBy = "monitorDevices")
    private Set monitorDevices = new HashSet(0);

    /**
     *
     */
    public Estado() {
    }

    /**
     *
     * @param idEstado
     */
    public Estado(int idEstado) {
        this.idEstado = idEstado;
    }

    /**
     *
     * @param idEstado
     * @param descEstado
     * @param monitorDevices
     */
    public Estado(int idEstado, String descEstado, Set monitorDevices) {
        this.idEstado = idEstado;
        this.descEstado = descEstado;
        this.monitorDevices = monitorDevices;
    }

    /**
     *
     * @return
     */
    public int getIdEstado() {
        return this.idEstado;
    }

    /**
     *
     * @param idEstado
     */
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    /**
     *
     * @return
     */
    public String getDescEstado() {
        return this.descEstado;
    }

    /**
     *
     * @param descEstado
     */
    public void setDescEstado(String descEstado) {
        this.descEstado = descEstado;
    }

    /**
     *
     * @return
     */
    public Set getMonitorDevices() {
        return this.monitorDevices;
    }

    /**
     *
     * @param monitorDevices
     */
    public void setMonitorDevices(Set monitorDevices) {
        this.monitorDevices = monitorDevices;
    }

}
