package com.dimacofi.DAO;
// Generated 13-03-2019 14:36:21 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIdentityReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * Impresora generated by hbm2java
 */
public class Impresora implements java.io.Serializable {

    private String codserie;

    @JsonProperty("contrato")
    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "contrato")
    @JsonIdentityReference(alwaysAsId = true)
    @ManyToOne
    @JoinColumn(name = "contrato")
    private ContratosMfp contratosMfp;

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "monitorDevice")
    private MonitorDevice monitorDevice;
    private Integer hh;
    private String modelo;
    private String marca;

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "valueses")
    private Set valueses = new HashSet(0);

    @JsonIgnore
    @OneToOne(mappedBy = "ip")
    private Ip ip;

    /**
     *
     */
    public Impresora() {
    }

    /**
     *
     * @param codserie
     * @param contratosMfp
     * @param modelo
     * @param marca
     */
    public Impresora(String codserie, ContratosMfp contratosMfp, String modelo, String marca) {
        this.codserie = codserie;
        this.contratosMfp = contratosMfp;
        this.modelo = modelo;
        this.marca = marca;
    }

    /**
     *
     * @param codserie
     * @param contratosMfp
     * @param monitorDevice
     * @param hh
     * @param modelo
     * @param marca
     * @param valueses
     * @param ip
     */
    public Impresora(String codserie, ContratosMfp contratosMfp, MonitorDevice monitorDevice, Integer hh, String modelo, String marca, Set valueses, Ip ip) {
        this.codserie = codserie;
        this.contratosMfp = contratosMfp;
        this.monitorDevice = monitorDevice;
        this.hh = hh;
        this.modelo = modelo;
        this.marca = marca;
        this.valueses = valueses;
        this.ip = ip;
    }

    /**
     *
     * @return
     */
    public String getCodserie() {
        return this.codserie;
    }

    /**
     *
     * @param codserie
     */
    public void setCodserie(String codserie) {
        this.codserie = codserie;
    }

    /**
     *
     * @return
     */
    public ContratosMfp getContratosMfp() {
        return this.contratosMfp;
    }

    /**
     *
     * @param contratosMfp
     */
    public void setContratosMfp(ContratosMfp contratosMfp) {
        this.contratosMfp = contratosMfp;
    }

    /**
     *
     * @return
     */
    public MonitorDevice getMonitorDevice() {
        return this.monitorDevice;
    }

    /**
     *
     * @param monitorDevice
     */
    public void setMonitorDevice(MonitorDevice monitorDevice) {
        this.monitorDevice = monitorDevice;
    }

    /**
     *
     * @return
     */
    public Integer getHh() {
        return this.hh;
    }

    /**
     *
     * @param hh
     */
    public void setHh(Integer hh) {
        this.hh = hh;
    }

    /**
     *
     * @return
     */
    public String getModelo() {
        return this.modelo;
    }

    /**
     *
     * @param modelo
     */
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    /**
     *
     * @return
     */
    public String getMarca() {
        return this.marca;
    }

    /**
     *
     * @param marca
     */
    public void setMarca(String marca) {
        this.marca = marca;
    }

    /**
     *
     * @return
     */
    public Set getValueses() {
        return this.valueses;
    }

    /**
     *
     * @param valueses
     */
    public void setValueses(Set valueses) {
        this.valueses = valueses;
    }

    /**
     *
     * @return
     */
    public Ip getIp() {
        return this.ip;
    }

    /**
     *
     * @param ip
     */
    public void setIp(Ip ip) {
        this.ip = ip;
    }

}
