package com.dimacofi.DAO;
// Generated 13-03-2019 14:36:21 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import javax.persistence.OneToOne;




/**
 * Ip generated by hbm2java
 */
public class Ip  implements java.io.Serializable {


    private String codserie;
     
     @JsonIgnore
     @OneToOne(mappedBy="impresora")
     private Impresora impresora;
     private String ip;

    public Ip() {
    }

    public Ip(Impresora impresora, String ip) {
       this.impresora = impresora;
       this.ip = ip;
    }
   
    public String getCodserie() {
        return this.codserie;
    }
    
    public void setCodserie(String codserie) {
        this.codserie = codserie;
    }
    public Impresora getImpresora() {
        return this.impresora;
    }
    
    public void setImpresora(Impresora impresora) {
        this.impresora = impresora;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }




}


