package com.dimacofi.DAO;
// Generated 18-04-2019 13:35:06 by Hibernate Tools 4.3.1



/**
 * MfpCodes generated by hbm2java
 */
public class MfpCodes  implements java.io.Serializable {


     private String nomModel;
     private String marca;
     private String imprColor;
     private String a3Color;
     private String b4Color;
     private String dupl;
     private String metro;
     private String copiaBn;
     private String copiaColor;
     private String imprBn;
     private String a3Bn;
     private String b4Bn;
     private String negro;
     private String cian;
     private String magenta;
     private String amarillo;
     private String scannerColor;
     private String scannerBn;
     private String negroMax;
     private String negroAct;
     private String cianMax;
     private String cianAct;
     private String magentaMax;
     private String magentaAct;
     private String amarilloMax;
     private String amarilloAct;

    /**
     *
     */
    public MfpCodes() {
    }

    /**
     *
     * @param nomModel
     * @param marca
     * @param copiaBn
     */
    public MfpCodes(String nomModel, String marca, String copiaBn) {
        this.nomModel = nomModel;
        this.marca = marca;
        this.copiaBn = copiaBn;
    }

    /**
     *
     * @param nomModel
     * @param marca
     * @param imprColor
     * @param a3Color
     * @param b4Color
     * @param dupl
     * @param metro
     * @param copiaBn
     * @param copiaColor
     * @param imprBn
     * @param a3Bn
     * @param b4Bn
     * @param negro
     * @param cian
     * @param magenta
     * @param amarillo
     * @param scannerColor
     * @param scannerBn
     * @param negroMax
     * @param negroAct
     * @param cianMax
     * @param cianAct
     * @param magentaMax
     * @param magentaAct
     * @param amarilloMax
     * @param amarilloAct
     */
    public MfpCodes(String nomModel, String marca, String imprColor, String a3Color, String b4Color, String dupl, String metro, String copiaBn, String copiaColor, String imprBn, String a3Bn, String b4Bn, String negro, String cian, String magenta, String amarillo, String scannerColor, String scannerBn, String negroMax, String negroAct, String cianMax, String cianAct, String magentaMax, String magentaAct, String amarilloMax, String amarilloAct) {
       this.nomModel = nomModel;
       this.marca = marca;
       this.imprColor = imprColor;
       this.a3Color = a3Color;
       this.b4Color = b4Color;
       this.dupl = dupl;
       this.metro = metro;
       this.copiaBn = copiaBn;
       this.copiaColor = copiaColor;
       this.imprBn = imprBn;
       this.a3Bn = a3Bn;
       this.b4Bn = b4Bn;
       this.negro = negro;
       this.cian = cian;
       this.magenta = magenta;
       this.amarillo = amarillo;
       this.scannerColor = scannerColor;
       this.scannerBn = scannerBn;
       this.negroMax = negroMax;
       this.negroAct = negroAct;
       this.cianMax = cianMax;
       this.cianAct = cianAct;
       this.magentaMax = magentaMax;
       this.magentaAct = magentaAct;
       this.amarilloMax = amarilloMax;
       this.amarilloAct = amarilloAct;
    }
   
    /**
     *
     * @return
     */
    public String getNomModel() {
        return this.nomModel;
    }
    
    /**
     *
     * @param nomModel
     */
    public void setNomModel(String nomModel) {
        this.nomModel = nomModel;
    }

    /**
     *
     * @return
     */
    public String getMarca() {
        return this.marca;
    }
    
    /**
     *
     * @param marca
     */
    public void setMarca(String marca) {
        this.marca = marca;
    }

    /**
     *
     * @return
     */
    public String getImprColor() {
        return this.imprColor;
    }
    
    /**
     *
     * @param imprColor
     */
    public void setImprColor(String imprColor) {
        this.imprColor = imprColor;
    }

    /**
     *
     * @return
     */
    public String getA3Color() {
        return this.a3Color;
    }
    
    /**
     *
     * @param a3Color
     */
    public void setA3Color(String a3Color) {
        this.a3Color = a3Color;
    }

    /**
     *
     * @return
     */
    public String getB4Color() {
        return this.b4Color;
    }
    
    /**
     *
     * @param b4Color
     */
    public void setB4Color(String b4Color) {
        this.b4Color = b4Color;
    }

    /**
     *
     * @return
     */
    public String getDupl() {
        return this.dupl;
    }
    
    /**
     *
     * @param dupl
     */
    public void setDupl(String dupl) {
        this.dupl = dupl;
    }

    /**
     *
     * @return
     */
    public String getMetro() {
        return this.metro;
    }
    
    /**
     *
     * @param metro
     */
    public void setMetro(String metro) {
        this.metro = metro;
    }

    /**
     *
     * @return
     */
    public String getCopiaBn() {
        return this.copiaBn;
    }
    
    /**
     *
     * @param copiaBn
     */
    public void setCopiaBn(String copiaBn) {
        this.copiaBn = copiaBn;
    }

    /**
     *
     * @return
     */
    public String getCopiaColor() {
        return this.copiaColor;
    }
    
    /**
     *
     * @param copiaColor
     */
    public void setCopiaColor(String copiaColor) {
        this.copiaColor = copiaColor;
    }

    /**
     *
     * @return
     */
    public String getImprBn() {
        return this.imprBn;
    }
    
    /**
     *
     * @param imprBn
     */
    public void setImprBn(String imprBn) {
        this.imprBn = imprBn;
    }

    /**
     *
     * @return
     */
    public String getA3Bn() {
        return this.a3Bn;
    }
    
    /**
     *
     * @param a3Bn
     */
    public void setA3Bn(String a3Bn) {
        this.a3Bn = a3Bn;
    }

    /**
     *
     * @return
     */
    public String getB4Bn() {
        return this.b4Bn;
    }
    
    /**
     *
     * @param b4Bn
     */
    public void setB4Bn(String b4Bn) {
        this.b4Bn = b4Bn;
    }

    /**
     *
     * @return
     */
    public String getNegro() {
        return this.negro;
    }
    
    /**
     *
     * @param negro
     */
    public void setNegro(String negro) {
        this.negro = negro;
    }

    /**
     *
     * @return
     */
    public String getCian() {
        return this.cian;
    }
    
    /**
     *
     * @param cian
     */
    public void setCian(String cian) {
        this.cian = cian;
    }

    /**
     *
     * @return
     */
    public String getMagenta() {
        return this.magenta;
    }
    
    /**
     *
     * @param magenta
     */
    public void setMagenta(String magenta) {
        this.magenta = magenta;
    }

    /**
     *
     * @return
     */
    public String getAmarillo() {
        return this.amarillo;
    }
    
    /**
     *
     * @param amarillo
     */
    public void setAmarillo(String amarillo) {
        this.amarillo = amarillo;
    }

    /**
     *
     * @return
     */
    public String getScannerColor() {
        return this.scannerColor;
    }
    
    /**
     *
     * @param scannerColor
     */
    public void setScannerColor(String scannerColor) {
        this.scannerColor = scannerColor;
    }

    /**
     *
     * @return
     */
    public String getScannerBn() {
        return this.scannerBn;
    }
    
    /**
     *
     * @param scannerBn
     */
    public void setScannerBn(String scannerBn) {
        this.scannerBn = scannerBn;
    }

    /**
     *
     * @return
     */
    public String getNegroMax() {
        return this.negroMax;
    }
    
    /**
     *
     * @param negroMax
     */
    public void setNegroMax(String negroMax) {
        this.negroMax = negroMax;
    }

    /**
     *
     * @return
     */
    public String getNegroAct() {
        return this.negroAct;
    }
    
    /**
     *
     * @param negroAct
     */
    public void setNegroAct(String negroAct) {
        this.negroAct = negroAct;
    }

    /**
     *
     * @return
     */
    public String getCianMax() {
        return this.cianMax;
    }
    
    /**
     *
     * @param cianMax
     */
    public void setCianMax(String cianMax) {
        this.cianMax = cianMax;
    }

    /**
     *
     * @return
     */
    public String getCianAct() {
        return this.cianAct;
    }
    
    /**
     *
     * @param cianAct
     */
    public void setCianAct(String cianAct) {
        this.cianAct = cianAct;
    }

    /**
     *
     * @return
     */
    public String getMagentaMax() {
        return this.magentaMax;
    }
    
    /**
     *
     * @param magentaMax
     */
    public void setMagentaMax(String magentaMax) {
        this.magentaMax = magentaMax;
    }

    /**
     *
     * @return
     */
    public String getMagentaAct() {
        return this.magentaAct;
    }
    
    /**
     *
     * @param magentaAct
     */
    public void setMagentaAct(String magentaAct) {
        this.magentaAct = magentaAct;
    }

    /**
     *
     * @return
     */
    public String getAmarilloMax() {
        return this.amarilloMax;
    }
    
    /**
     *
     * @param amarilloMax
     */
    public void setAmarilloMax(String amarilloMax) {
        this.amarilloMax = amarilloMax;
    }

    /**
     *
     * @return
     */
    public String getAmarilloAct() {
        return this.amarilloAct;
    }
    
    /**
     *
     * @param amarilloAct
     */
    public void setAmarilloAct(String amarilloAct) {
        this.amarilloAct = amarilloAct;
    }




}


