package com.dimacofi.DAO;
// Generated 13-03-2019 14:36:21 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * MonitorDevice generated by hbm2java
 */
public class MonitorDevice  implements java.io.Serializable {

 private int idDevice;
     
     @ManyToOne
     @JoinColumn(name="estado")
     private Estado estado;
     
     @ManyToOne
     @JoinColumn(name="typeDevice")
     private TypeDevice typeDevice;
     
     private String mac;
     private String ip;
     
     @JsonIgnore
     @OneToMany(mappedBy="impresoras")
     private Set impresoras = new HashSet(0);

    public MonitorDevice() {
    }

	
    public MonitorDevice(int idDevice, TypeDevice typeDevice, String mac) {
        this.idDevice = idDevice;
        this.typeDevice = typeDevice;
        this.mac = mac;
    }
    public MonitorDevice(int idDevice, Estado estado, TypeDevice typeDevice, String mac, String ip, Set impresoras) {
       this.idDevice = idDevice;
       this.estado = estado;
       this.typeDevice = typeDevice;
       this.mac = mac;
       this.ip = ip;
       this.impresoras = impresoras;
    }
   
    public int getIdDevice() {
        return this.idDevice;
    }
    
    public void setIdDevice(int idDevice) {
        this.idDevice = idDevice;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public TypeDevice getTypeDevice() {
        return this.typeDevice;
    }
    
    public void setTypeDevice(TypeDevice typeDevice) {
        this.typeDevice = typeDevice;
    }
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Set getImpresoras() {
        return this.impresoras;
    }
    
    public void setImpresoras(Set impresoras) {
        this.impresoras = impresoras;
    }




}


