package com.dimacofi.DAO;
// Generated 18-04-2019 13:35:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MonitorDevice generated by hbm2java
 */
public class MonitorDevice  implements java.io.Serializable {


     private int idDevice;
     private Estado estado;
     private TypeDevice typeDevice;
     private String mac;
     private String ip;
     private Set impresoras = new HashSet(0);

    /**
     *
     */
    public MonitorDevice() {
    }

    /**
     *
     * @param idDevice
     * @param typeDevice
     * @param mac
     */
    public MonitorDevice(int idDevice, TypeDevice typeDevice, String mac) {
        this.idDevice = idDevice;
        this.typeDevice = typeDevice;
        this.mac = mac;
    }

    /**
     *
     * @param idDevice
     * @param estado
     * @param typeDevice
     * @param mac
     * @param ip
     * @param impresoras
     */
    public MonitorDevice(int idDevice, Estado estado, TypeDevice typeDevice, String mac, String ip, Set impresoras) {
       this.idDevice = idDevice;
       this.estado = estado;
       this.typeDevice = typeDevice;
       this.mac = mac;
       this.ip = ip;
       this.impresoras = impresoras;
    }
   
    /**
     *
     * @return
     */
    public int getIdDevice() {
        return this.idDevice;
    }
        /**
     *
     * @param idDevice
     */

    public void setIdDevice(int idDevice) {
        this.idDevice = idDevice;
    }

    /**
     *
     * @return
     */
    public Estado getEstado() {
        return this.estado;
    }
    
    /**
     *
     * @param estado
     */
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    /**
     *
     * @return
     */
    public TypeDevice getTypeDevice() {
        return this.typeDevice;
    }
    
    /**
     *
     * @param typeDevice
     */
    public void setTypeDevice(TypeDevice typeDevice) {
        this.typeDevice = typeDevice;
    }

    /**
     *
     * @return
     */
    public String getMac() {
        return this.mac;
    }
    
    /**
     *
     * @param mac
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     *
     * @return
     */
    public String getIp() {
        return this.ip;
    }
    
    /**
     *
     * @param ip
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     *
     * @return
     */
    public Set getImpresoras() {
        return this.impresoras;
    }
    
    /**
     *
     * @param impresoras
     */
    public void setImpresoras(Set impresoras) {
        this.impresoras = impresoras;
    }




}


