package com.dimacofi.DAO;
// Generated 18-04-2019 13:35:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TypeDevice generated by hbm2java
 */
public class TypeDevice  implements java.io.Serializable {


     private short type;
     private String descripcion;
     private Set monitorDevices = new HashSet(0);

    /**
     *
     */
    public TypeDevice() {
    }

    /**
     *
     * @param type
     * @param descripcion
     */
    public TypeDevice(short type, String descripcion) {
        this.type = type;
        this.descripcion = descripcion;
    }

    /**
     *
     * @param type
     * @param descripcion
     * @param monitorDevices
     */
    public TypeDevice(short type, String descripcion, Set monitorDevices) {
       this.type = type;
       this.descripcion = descripcion;
       this.monitorDevices = monitorDevices;
    }
   
    /**
     *
     * @return
     */
    public short getType() {
        return this.type;
    }
    
    /**
     *
     * @param type
     */
    public void setType(short type) {
        this.type = type;
    }

    /**
     *
     * @return
     */
    public String getDescripcion() {
        return this.descripcion;
    }
    
    /**
     *
     * @param descripcion
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     *
     * @return
     */
    public Set getMonitorDevices() {
        return this.monitorDevices;
    }
        /**
     *
     * @param monitorDevices
     */

    public void setMonitorDevices(Set monitorDevices) {
        this.monitorDevices = monitorDevices;
    }




}


