package com.dimacofi.DAO;
// Generated 13-03-2019 14:36:21 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Values generated by hbm2java
 */
public class Values implements java.io.Serializable {

    private int idValues;

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "impresora")
    private Impresora impresora;
    private int copiaColor;
    private int copiaBn;
    private int scannerColor;
    private int scannerBn;
    private int a3Color;
    private int b4Color;
    private int a3Bn;
    private int b4Bn;
    private int metro;
    private int dupl;
    private int negro;
    private int cian;
    private int magenta;
    private int amarillo;
    private int imprColor;
    private int imprBn;

    @Temporal(TemporalType.TIMESTAMP)
    private Date fechaMuestra;

    public Values() {
    }

    public Values(int idValues, Impresora impresora, int copiaColor, int copiaBn, int scanerColor, int scanerBn, int a3Color, int b4Color, int a3Bn, int b4Bn, int metro, int dupl, int negro, int cian, int magenta, int amarillo, int imprColor, int imprBn, Date fechaMuestra) {
        this.idValues = idValues;
        this.impresora = impresora;
        this.copiaColor = copiaColor;
        this.copiaBn = copiaBn;
        this.scannerColor = scanerColor;
        this.scannerBn = scanerBn;
        this.a3Color = a3Color;
        this.b4Color = b4Color;
        this.a3Bn = a3Bn;
        this.b4Bn = b4Bn;
        this.metro = metro;
        this.dupl = dupl;
        this.negro = negro;
        this.cian = cian;
        this.magenta = magenta;
        this.amarillo = amarillo;
        this.imprColor = imprColor;
        this.imprBn = imprBn;
        this.fechaMuestra = fechaMuestra;
    }

    public int getIdValues() {
        return idValues;
    }

    public void setIdValues(int idValues) {
        this.idValues = idValues;
    }

    public Impresora getImpresora() {
        return impresora;
    }

    public void setImpresora(Impresora impresora) {
        this.impresora = impresora;
    }

    public int getCopiaColor() {
        return copiaColor;
    }

    public void setCopiaColor(int copiaColor) {
        this.copiaColor = copiaColor;
    }

    public int getCopiaBn() {
        return copiaBn;
    }

    public void setCopiaBn(int copiaBn) {
        this.copiaBn = copiaBn;
    }

    public int getScannerColor() {
        return scannerColor;
    }

    public void setScannerColor(int scannerColor) {
        this.scannerColor = scannerColor;
    }

    public int getScannerBn() {
        return scannerBn;
    }

    public void setScannerBn(int scannerBn) {
        this.scannerBn = scannerBn;
    }

    public int getA3Color() {
        return a3Color;
    }

    public void setA3Color(int a3Color) {
        this.a3Color = a3Color;
    }

    public int getB4Color() {
        return b4Color;
    }

    public void setB4Color(int b4Color) {
        this.b4Color = b4Color;
    }

    public int getA3Bn() {
        return a3Bn;
    }

    public void setA3Bn(int a3Bn) {
        this.a3Bn = a3Bn;
    }

    public int getB4Bn() {
        return b4Bn;
    }

    public void setB4Bn(int b4Bn) {
        this.b4Bn = b4Bn;
    }

    public int getMetro() {
        return metro;
    }

    public void setMetro(int metro) {
        this.metro = metro;
    }

    public int getDupl() {
        return dupl;
    }

    public void setDupl(int dupl) {
        this.dupl = dupl;
    }

    public int getNegro() {
        return negro;
    }

    public void setNegro(int negro) {
        this.negro = negro;
    }

    public int getCian() {
        return cian;
    }

    public void setCian(int cian) {
        this.cian = cian;
    }

    public int getMagenta() {
        return magenta;
    }

    public void setMagenta(int magenta) {
        this.magenta = magenta;
    }

    public int getAmarillo() {
        return amarillo;
    }

    public void setAmarillo(int amarillo) {
        this.amarillo = amarillo;
    }

    public int getImprColor() {
        return imprColor;
    }

    public void setImprColor(int imprColor) {
        this.imprColor = imprColor;
    }

    public int getImprBn() {
        return imprBn;
    }

    public void setImprBn(int imprBn) {
        this.imprBn = imprBn;
    }

    public Date getFechaMuestra() {
        return fechaMuestra;
    }

    public void setFechaMuestra(Date fechaMuestra) {
        this.fechaMuestra = fechaMuestra;
    }

    
   
}
