package com.dimacofi.DAO;
// Generated 18-04-2019 13:35:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Values generated by hbm2java
 */
public class Values  implements java.io.Serializable {


     private long idValues;
     private Impresora impresora;
     private Integer imprColor;
     private Integer imprBn;
     private Integer copiaColor;
     private Integer copiaBn;
     private Integer a3Color;
     private Integer b4Color;
     private Integer metro;
     private Integer dupl;
     private Date fechaMuestra;
     private Integer a3Bn;
     private Integer b4Bn;
     private Integer negro;
     private Integer cian;
     private Integer magenta;
     private Integer amarillo;
     private Integer color;
     private Integer scannerColor;
     private Integer scannerBn;

    /**
     *
     */
    public Values() {
    }

    /**
     *
     * @param idValues
     */
    public Values(long idValues) {
        this.idValues = idValues;
    }

    /**
     *
     * @param idValues
     * @param impresora
     * @param imprColor
     * @param imprBn
     * @param copiaColor
     * @param copiaBn
     * @param a3Color
     * @param b4Color
     * @param metro
     * @param dupl
     * @param fechaMuestra
     * @param a3Bn
     * @param b4Bn
     * @param negro
     * @param cian
     * @param magenta
     * @param amarillo
     * @param color
     * @param scannerColor
     * @param scannerBn
     */
    public Values(long idValues, Impresora impresora, Integer imprColor, Integer imprBn, Integer copiaColor, Integer copiaBn, Integer a3Color, Integer b4Color, Integer metro, Integer dupl, Date fechaMuestra, Integer a3Bn, Integer b4Bn, Integer negro, Integer cian, Integer magenta, Integer amarillo, Integer color, Integer scannerColor, Integer scannerBn) {
       this.idValues = idValues;
       this.impresora = impresora;
       this.imprColor = imprColor;
       this.imprBn = imprBn;
       this.copiaColor = copiaColor;
       this.copiaBn = copiaBn;
       this.a3Color = a3Color;
       this.b4Color = b4Color;
       this.metro = metro;
       this.dupl = dupl;
       this.fechaMuestra = fechaMuestra;
       this.a3Bn = a3Bn;
       this.b4Bn = b4Bn;
       this.negro = negro;
       this.cian = cian;
       this.magenta = magenta;
       this.amarillo = amarillo;
       this.color = color;
       this.scannerColor = scannerColor;
       this.scannerBn = scannerBn;
    }
   
    /**
     *
     * @return
     */
    public long getIdValues() {
        return this.idValues;
    }
    
    /**
     *
     * @param idValues
     */
    public void setIdValues(long idValues) {
        this.idValues = idValues;
    }

    /**
     *
     * @return
     */
    public Impresora getImpresora() {
        return this.impresora;
    }
    
    /**
     *
     * @param impresora
     */
    public void setImpresora(Impresora impresora) {
        this.impresora = impresora;
    }

    /**
     *
     * @return
     */
    public Integer getImprColor() {
        return this.imprColor;
    }
    
    /**
     *
     * @param imprColor
     */
    public void setImprColor(Integer imprColor) {
        this.imprColor = imprColor;
    }

    /**
     *
     * @return
     */
    public Integer getImprBn() {
        return this.imprBn;
    }
    
    /**
     *
     * @param imprBn
     */
    public void setImprBn(Integer imprBn) {
        this.imprBn = imprBn;
    }

    /**
     *
     * @return
     */
    public Integer getCopiaColor() {
        return this.copiaColor;
    }
    
    /**
     *
     * @param copiaColor
     */
    public void setCopiaColor(Integer copiaColor) {
        this.copiaColor = copiaColor;
    }

    /**
     *
     * @return
     */
    public Integer getCopiaBn() {
        return this.copiaBn;
    }
    
    /**
     *
     * @param copiaBn
     */
    public void setCopiaBn(Integer copiaBn) {
        this.copiaBn = copiaBn;
    }

    /**
     *
     * @return
     */
    public Integer getA3Color() {
        return this.a3Color;
    }
    
    /**
     *
     * @param a3Color
     */
    public void setA3Color(Integer a3Color) {
        this.a3Color = a3Color;
    }

    /**
     *
     * @return
     */
    public Integer getB4Color() {
        return this.b4Color;
    }
    
    /**
     *
     * @param b4Color
     */
    public void setB4Color(Integer b4Color) {
        this.b4Color = b4Color;
    }

    /**
     *
     * @return
     */
    public Integer getMetro() {
        return this.metro;
    }
    
    /**
     *
     * @param metro
     */
    public void setMetro(Integer metro) {
        this.metro = metro;
    }

    /**
     *
     * @return
     */
    public Integer getDupl() {
        return this.dupl;
    }
    
    /**
     *
     * @param dupl
     */
    public void setDupl(Integer dupl) {
        this.dupl = dupl;
    }

    /**
     *
     * @return
     */
    public Date getFechaMuestra() {
        return this.fechaMuestra;
    }
    
    /**
     *
     * @param fechaMuestra
     */
    public void setFechaMuestra(Date fechaMuestra) {
        this.fechaMuestra = fechaMuestra;
    }

    /**
     *
     * @return
     */
    public Integer getA3Bn() {
        return this.a3Bn;
    }
    
    /**
     *
     * @param a3Bn
     */
    public void setA3Bn(Integer a3Bn) {
        this.a3Bn = a3Bn;
    }

    /**
     *
     * @return
     */
    public Integer getB4Bn() {
        return this.b4Bn;
    }
    
    /**
     *
     * @param b4Bn
     */
    public void setB4Bn(Integer b4Bn) {
        this.b4Bn = b4Bn;
    }

    /**
     *
     * @return
     */
    public Integer getNegro() {
        return this.negro;
    }
        /**
     *
     * @param negro
     */

    public void setNegro(Integer negro) {
        this.negro = negro;
    }

    /**
     *
     * @return
     */
    public Integer getCian() {
        return this.cian;
    }
    
    /**
     *
     * @param cian
     */
    public void setCian(Integer cian) {
        this.cian = cian;
    }

    /**
     *
     * @return
     */
    public Integer getMagenta() {
        return this.magenta;
    }
    
    /**
     *
     * @param magenta
     */
    public void setMagenta(Integer magenta) {
        this.magenta = magenta;
    }

    /**
     *
     * @return
     */
    public Integer getAmarillo() {
        return this.amarillo;
    }
    
    /**
     *
     * @param amarillo
     */
    public void setAmarillo(Integer amarillo) {
        this.amarillo = amarillo;
    }

    /**
     *
     * @return
     */
    public Integer getColor() {
        return this.color;
    }
    
    /**
     *
     * @param color
     */
    public void setColor(Integer color) {
        this.color = color;
    }

    /**
     *
     * @return
     */
    public Integer getScannerColor() {
        return this.scannerColor;
    }
    
    /**
     *
     * @param scannerColor
     */
    public void setScannerColor(Integer scannerColor) {
        this.scannerColor = scannerColor;
    }

    /**
     *
     * @return
     */
    public Integer getScannerBn() {
        return this.scannerBn;
    }
    
    /**
     *
     * @param scannerBn
     */
    public void setScannerBn(Integer scannerBn) {
        this.scannerBn = scannerBn;
    }




}


